import sqlite3
conn = sqlite3.connect(r"C:\Users\Avi Schwartz\Documents\hasidic-footage-scan\output\shtetlframes.db")
cur = conn.cursor()
cur.execute("SELECT COUNT(*) FROM queue_items WHERE hub_url='britishpathe.com' AND status='pending'")
print("pending britishpathe.com total:", cur.fetchone()[0])
cur.execute("SELECT COUNT(*) FROM queue_items WHERE hub_url='britishpathe.com' AND status='pending' AND title LIKE 'British Path%'")
print("pending title LIKE 'British Path%':", cur.fetchone()[0])
cur.execute("SELECT COUNT(*) FROM queue_items WHERE hub_url='britishpathe.com' AND title LIKE '%asset %'")
print("title LIKE '%asset %':", cur.fetchone()[0])
cur.execute("PRAGMA table_info(candidates)")
print("candidates cols:", [r[1] for r in cur.fetchall()])
cur.execute("SELECT notes FROM candidates WHERE notes IS NOT NULL AND notes != '' LIMIT 3")
print("candidates notes samples:", cur.fetchall())
conn.close()
